version: "3"
services:

  app:
    build:
      context: "."
      dockerfile: app.dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: abc
      DB_USERNAME: abc
      DB_PASSWORD: password
      SEED_USERNAME: seedyweedy
      SEED_PASSWORD: password
    ports:
      - "13000:80"
    depends_on: [db]
    restart: always
  db:
    image: postgres:9.6.2
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: password
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.db:/var/lib/postgresql/data
